### ISSUE TITLE
2.8 checklist

### ISSUE THREAD

**Issue by jdent02** [prman-pixar/RenderManForBlender#587]
- [ ] Object retrieval needs to migrate to the depsgraph that is provided with the bpy.types.RenderEngine functions.

- [ ] UI needs reformatting.  The 2.8 default 'single column' style layout would make it visually consistent with Cycles.

- [ ] Scene update 'post' function has been removed.  Last I checked that was still powering the interactive render update.

Some bugs and glitches:

- [ ] Light filter 'gobo' objects in the viewport usually don't match the visual results of the render.  Not sure if the issue is in the gobo object or the filter parameter export.

- [ ] Internal render feedback is a bit inconsistent.  Sometimes the image doesn't update at all during rendering.

- [ ] Dynamic lists for linking lights/light groups to objects/Object groups is neat but still a bit glitchy.

- [ ] Cancelling an in progress render will usually cause Blender to crash if you try to start a new render.

- [ ] Mixing and matching area lamp 'size' parameters with object scaling causes visual inconsistencies.

**Comment by LoganxDev** [comment]
Is this currently being worked on?
